#11 Validations on SignUp Screen
BC-MAR-21-RN/kata-05-reservacion-vuelo-equipo-02-k05-reservacion-vuelo pull request #15
Opened 2021-04-15 19:11 UTC by OrlandoAlPe

Completed the following validations for the SignUp Screen:

- Name TextInput
- Email TextInput
- Password TextInpt
- Term and policy agreement checkbox

The app verifies if those validations are passed or not with an alert message.

![Screenshot_1618513521](https://user-images.githubusercontent.com/33968113/114924596-c86afa80-9df3-11eb-9bbc-cc3d0817703a.png)

![Screenshot_1618513683](https://user-images.githubusercontent.com/33968113/114924846-049e5b00-9df4-11eb-8dd1-9c649acd30b1.png)

Firebase SignUp services are Still pending.

2021-04-17 04:14 UTC, jkzasori reviewed
Are you using codeclima? I'm asking because I can't see at the bottom...

2021-04-19 17:48 UTC, Coreandrum1 commented
> Are you using codeclima? I'm asking because I can't see at the bottom...

2021-04-19 17:49 UTC, OrlandoAlPe commented
> Are you using codeclima? I'm asking because I can't see at the bottom...
The repostory is private so we can´t implement code climate yet.

2021-04-19 17:49 UTC, Coreandrum1 reviewed
LGTM

2021-04-19 22:42 UTC, Joaquin-Niembro commented on reservacionVuelo/Screens/SignUp.js
> +const nameRegex = /^[A-Za-z]+$/;
Put this expressions in a constants file

2021-04-19 22:43 UTC, Joaquin-Niembro commented on reservacionVuelo/Screens/SignUp.js
> +          errorMessage={'Write a valid name please'}
Put the errorMessage in a constants file

2021-04-19 22:45 UTC, Joaquin-Niembro requested changes

2021-04-19 22:45 UTC, Joaquin-Niembro commented on reservacionVuelo/Screens/SignUp.js
> +          errorMessage={'Terms and privacy policy must be checked'}
Put these messages and texts in a constants file

2021-04-19 22:45 UTC, Joaquin-Niembro commented on reservacionVuelo/components/checkbox.js
> +  }
Remove the constructor if its not in use

2021-04-20 19:28 UTC, Joaquin-Niembro approved these changes

2021-04-21 16:27 UTC, Coreandrum1 approved these changes

2021-04-23 22:39 UTC, DiegoSpielzeug commented
why don't you have CodeClimate and Deepscan?

2021-04-24 03:04 UTC, jkzasori approved these changes

2021-04-24 03:08 UTC, merged